name: Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Account Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jessdhy/webpage:${{ github.sha }}
          
      - name: Deploy instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop webpage || true
            sudo docker rm webpage || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/webpage:${{ github.sha }}
            sudo docker run -d --name webpage -p 80:80 ${{ secrets.DOCKER_USERNAME }}/webpage:${{ github.sha }}